// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
)

// Defines values for CaseStatus.
const (
	Blocked   CaseStatus = "blocked"
	Cancelled CaseStatus = "cancelled"
	Completed CaseStatus = "completed"
	Open      CaseStatus = "open"
	Started   CaseStatus = "started"
)

// Valid indicates whether the value is a known member of the CaseStatus enum.
func (e CaseStatus) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Cancelled:
		return true
	case Completed:
		return true
	case Open:
		return true
	case Started:
		return true
	default:
		return false
	}
}

// Defines values for ResourceType.
const (
	AGENT     ResourceType = "AGENT"
	CASE      ResourceType = "CASE"
	FILE      ResourceType = "FILE"
	NOTE      ResourceType = "NOTE"
	PROCEDURE ResourceType = "PROCEDURE"
	SPACE     ResourceType = "SPACE"
	THREAD    ResourceType = "THREAD"
	USER      ResourceType = "USER"
)

// Valid indicates whether the value is a known member of the ResourceType enum.
func (e ResourceType) Valid() bool {
	switch e {
	case AGENT:
		return true
	case CASE:
		return true
	case FILE:
		return true
	case NOTE:
		return true
	case PROCEDURE:
		return true
	case SPACE:
		return true
	case THREAD:
		return true
	case USER:
		return true
	default:
		return false
	}
}

// Defines values for ListCasesParamsSort.
const (
	ListCasesParamsSortCreatedAt ListCasesParamsSort = "created_at"
	ListCasesParamsSortPosition  ListCasesParamsSort = "position"
	ListCasesParamsSortUpdatedAt ListCasesParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListCasesParamsSort enum.
func (e ListCasesParamsSort) Valid() bool {
	switch e {
	case ListCasesParamsSortCreatedAt:
		return true
	case ListCasesParamsSortPosition:
		return true
	case ListCasesParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListCasesParamsDirection.
const (
	ListCasesParamsDirectionAsc  ListCasesParamsDirection = "asc"
	ListCasesParamsDirectionDesc ListCasesParamsDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListCasesParamsDirection enum.
func (e ListCasesParamsDirection) Valid() bool {
	switch e {
	case ListCasesParamsDirectionAsc:
		return true
	case ListCasesParamsDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsSort.
const (
	ListFilesParamsSortCreatedAt ListFilesParamsSort = "created_at"
	ListFilesParamsSortUpdatedAt ListFilesParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListFilesParamsSort enum.
func (e ListFilesParamsSort) Valid() bool {
	switch e {
	case ListFilesParamsSortCreatedAt:
		return true
	case ListFilesParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsDirection.
const (
	ListFilesParamsDirectionAsc  ListFilesParamsDirection = "asc"
	ListFilesParamsDirectionDesc ListFilesParamsDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListFilesParamsDirection enum.
func (e ListFilesParamsDirection) Valid() bool {
	switch e {
	case ListFilesParamsDirectionAsc:
		return true
	case ListFilesParamsDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListNotesParamsSort.
const (
	CreatedAt ListNotesParamsSort = "created_at"
	UpdatedAt ListNotesParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListNotesParamsSort enum.
func (e ListNotesParamsSort) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListNotesParamsDirection.
const (
	ListNotesParamsDirectionAsc  ListNotesParamsDirection = "asc"
	ListNotesParamsDirectionDesc ListNotesParamsDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListNotesParamsDirection enum.
func (e ListNotesParamsDirection) Valid() bool {
	switch e {
	case ListNotesParamsDirectionAsc:
		return true
	case ListNotesParamsDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListThreadEventsParamsDirection.
const (
	ListThreadEventsParamsDirectionAsc  ListThreadEventsParamsDirection = "asc"
	ListThreadEventsParamsDirectionDesc ListThreadEventsParamsDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListThreadEventsParamsDirection enum.
func (e ListThreadEventsParamsDirection) Valid() bool {
	switch e {
	case ListThreadEventsParamsDirectionAsc:
		return true
	case ListThreadEventsParamsDirectionDesc:
		return true
	default:
		return false
	}
}

// AdditionalMetadata defines model for AdditionalMetadata.
type AdditionalMetadata map[string]interface{}

// Agent defines model for Agent.
type Agent struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// JobDescription Optional job description used when the agent acts.
	JobDescription *string `json:"job_description,omitempty"`

	// Model Effective model used by the agent. If the stored model is null, the configured default model is used.
	Model string `json:"model"`

	// Name Human-readable agent name.
	Name   string        `json:"name"`
	Parent *ResourceLink `json:"parent,omitempty"`

	// Type Public resource type for the agent.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// AgentListItem defines model for AgentListItem.
type AgentListItem struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// Model Effective model used by the agent. If the stored model is null, the configured default model is used.
	Model string `json:"model"`

	// Name Human-readable agent name.
	Name   string        `json:"name"`
	Parent *ResourceLink `json:"parent,omitempty"`

	// Type Public resource type for the agent.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// Case defines model for Case.
type Case struct {
	Assignee *ResourceLink `json:"assignee,omitempty"`

	// CompletedAt Timestamp when the case was completed, if completed.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Description Optional detailed description or instructions for the case.
	Description *string `json:"description,omitempty"`

	// DueAt Optional deadline for the case.
	DueAt *time.Time `json:"due_at,omitempty"`

	// ExternalId Optional caller-provided identifier for linking to an external system.
	ExternalId *string `json:"external_id,omitempty"`

	// Files Files attached to the case, represented as public File links.
	Files *[]ResourceLink `json:"files,omitempty"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`
	Status CaseStatus         `json:"status"`

	// Summary Optional generated or user-provided case summary.
	Summary *string `json:"summary,omitempty"`

	// Tags Tags assigned to the case, represented as simple names.
	Tags   *[]string    `json:"tags,omitempty"`
	Thread ResourceLink `json:"thread"`

	// Title Human-readable case name.
	Title string `json:"title"`

	// Type Public resource type for the case.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// CaseListItem defines model for CaseListItem.
type CaseListItem struct {
	Assignee *ResourceLink `json:"assignee,omitempty"`

	// CompletedAt Timestamp when the case was completed, if completed.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// DueAt Optional deadline for the case.
	DueAt *time.Time `json:"due_at,omitempty"`

	// ExternalId Optional caller-provided identifier for linking to an external system.
	ExternalId *string `json:"external_id,omitempty"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`
	Status CaseStatus         `json:"status"`

	// Tags Tags assigned to the case, represented as simple names.
	Tags *[]string `json:"tags,omitempty"`

	// Title Human-readable case name.
	Title string `json:"title"`

	// Type Public resource type for the case.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// CaseStatus defines model for CaseStatus.
type CaseStatus string

// CreateAgentRequest defines model for CreateAgentRequest.
type CreateAgentRequest struct {
	JobDescription *string `json:"job_description,omitempty"`

	// Model Optional model used by the agent. Set to null or omit to use the configured default model.
	Model *string `json:"model,omitempty"`
	Name  string  `json:"name"`
}

// CreateCaseRequest defines model for CreateCaseRequest.
type CreateCaseRequest struct {
	AssigneeId      *openapi_types.UUID   `json:"assignee_id,omitempty"`
	AttachedFileIds *[]openapi_types.UUID `json:"attached_file_ids,omitempty"`
	Description     *string               `json:"description,omitempty"`
	DueAt           *time.Time            `json:"due_at,omitempty"`
	ExternalId      *string               `json:"external_id,omitempty"`

	// ParentCaseId Parent Case ID for a child case. Provide exactly one of space_id or parent_case_id.
	ParentCaseId *openapi_types.UUID `json:"parent_case_id,omitempty"`

	// SpaceId Target Space ID for a root case. Provide exactly one of space_id or parent_case_id.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
	Title   string              `json:"title"`
}

// CreateFileRequest defines model for CreateFileRequest.
type CreateFileRequest struct {
	// CaseId Target Case ID for a case-owned file. Provide at most one of space_id or case_id.
	CaseId *openapi_types.UUID `json:"case_id,omitempty"`

	// File File to upload.
	File openapi_types.File `json:"file"`

	// SpaceId Target Space ID for a space-owned file. Provide at most one of space_id or case_id.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
}

// CreateMessageRequest defines model for CreateMessageRequest.
type CreateMessageRequest struct {
	Text string `json:"text"`
}

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Body *string `json:"body,omitempty"`

	// CaseId Target Case ID. Provide exactly one of space_id or case_id.
	CaseId *openapi_types.UUID `json:"case_id,omitempty"`

	// SpaceId Target Space ID. Provide exactly one of space_id or case_id.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
	Title   string              `json:"title"`
}

// CreateProcedureRequest defines model for CreateProcedureRequest.
type CreateProcedureRequest struct {
	// SpaceId Space ID that owns the procedure.
	SpaceId openapi_types.UUID `json:"space_id"`

	// Title Human-readable procedure name.
	Title string `json:"title"`
}

// CreateSpaceRequest defines model for CreateSpaceRequest.
type CreateSpaceRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	// CreatedAt Timestamp when the user was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the user.
	Id openapi_types.UUID `json:"id"`

	// IsPending True when the user has been invited but has not yet signed in via Zitadel.
	IsPending bool `json:"is_pending"`

	// Name Display name for the user.
	Name         string       `json:"name"`
	Organization Organization `json:"organization"`

	// Type Public resource type for the user.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the user was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// File defines model for File.
type File struct {
	AdditionalMetadata *AdditionalMetadata `json:"additional_metadata,omitempty"`

	// CreatedAt Timestamp when the file was created.
	CreatedAt time.Time `json:"created_at"`

	// DownloadUrl Short-lived signed URL for downloading the file bytes.
	DownloadUrl string `json:"download_url"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// MimeType Detected MIME type for the file.
	MimeType string `json:"mime_type"`

	// Name Original or generated display name for the file.
	Name   string        `json:"name"`
	Parent *ResourceLink `json:"parent,omitempty"`

	// Size File size in bytes.
	Size int `json:"size"`

	// Tags Tags assigned to the file, represented as simple names.
	Tags *[]string `json:"tags,omitempty"`

	// Type Public resource type for the file.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the file was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// FilePayload defines model for FilePayload.
type FilePayload struct {
	File        ResourceLink `json:"file"`
	PayloadType string       `json:"payload_type"`
}

// GameObject defines model for GameObject.
type GameObject struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`
	Type   ResourceType       `json:"type"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ListAgentsResponse defines model for ListAgentsResponse.
type ListAgentsResponse struct {
	// Data Items in the current page.
	Data []AgentListItem `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListCasesResponse defines model for ListCasesResponse.
type ListCasesResponse struct {
	// Data Items in the current page.
	Data []CaseListItem `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListFilesResponse defines model for ListFilesResponse.
type ListFilesResponse struct {
	// Data Items in the current page.
	Data []File `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListNotesResponse defines model for ListNotesResponse.
type ListNotesResponse struct {
	// Data Items in the current page.
	Data []NoteListItem `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListProceduresResponse defines model for ListProceduresResponse.
type ListProceduresResponse struct {
	// Data Items in the current page.
	Data []ProcedureSummary `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListSpacesResponse defines model for ListSpacesResponse.
type ListSpacesResponse struct {
	// Data Items in the current page.
	Data []SpaceListItem `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListThreadEventsResponse defines model for ListThreadEventsResponse.
type ListThreadEventsResponse struct {
	// Data Items in the current page.
	Data []ThreadEvent `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse struct {
	// Data Items in the current page.
	Data []User `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// MessagePayload defines model for MessagePayload.
type MessagePayload struct {
	PayloadType string `json:"payload_type"`
	Text        string `json:"text"`
}

// Note defines model for Note.
type Note struct {
	// Body Optional note body.
	Body *string `json:"body,omitempty"`

	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`

	// Tags Tags assigned to the note, represented as simple names.
	Tags *[]string `json:"tags,omitempty"`

	// Title Human-readable note title.
	Title string `json:"title"`

	// Type Public resource type for the note.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// NoteListItem defines model for NoteListItem.
type NoteListItem struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`

	// Tags Tags assigned to the note, represented as simple names.
	Tags *[]string `json:"tags,omitempty"`

	// Title Human-readable note title.
	Title string `json:"title"`

	// Type Public resource type for the note.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// Organization defines model for Organization.
type Organization struct {
	// Id Unique identifier for the organization.
	Id openapi_types.UUID `json:"id"`

	// Name Display name for the organization.
	Name string `json:"name"`

	// Slug URL-safe slug for the organization.
	Slug string `json:"slug"`
}

// Procedure defines model for Procedure.
type Procedure struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`

	// Stages Procedure stages, in procedure order.
	Stages *[]ProcedureStage `json:"stages,omitempty"`

	// Title Human-readable procedure name.
	Title string `json:"title"`

	// Type Public resource type for the procedure.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ProcedureStage defines model for ProcedureStage.
type ProcedureStage struct {
	Assignee *ResourceLink `json:"assignee,omitempty"`

	// CreatedAt Timestamp when the stage was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the procedure stage.
	Id openapi_types.UUID `json:"id"`

	// Instructions Optional instructions for the stage.
	Instructions *string `json:"instructions,omitempty"`

	// Title Optional human-readable stage title.
	Title *string `json:"title,omitempty"`

	// UpdatedAt Timestamp when the stage was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ProcedureStagePatchRequest defines model for ProcedureStagePatchRequest.
type ProcedureStagePatchRequest struct {
	// AssigneeId User ID assigned to the stage, or null for no assignee.
	AssigneeId *openapi_types.UUID `json:"assignee_id"`

	// Id Existing stage ID. Omit to create a new stage.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Instructions Stage instructions, or null for no instructions.
	Instructions *string `json:"instructions"`

	// Title Stage title, or null for no title.
	Title *string `json:"title"`
}

// ProcedureSummary defines model for ProcedureSummary.
type ProcedureSummary struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`

	// Title Human-readable procedure name.
	Title string `json:"title"`

	// Type Public resource type for the procedure.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ResourceLink defines model for ResourceLink.
type ResourceLink struct {
	// Id Unique identifier for the linked object.
	Id   openapi_types.UUID `json:"id"`
	Type ResourceType       `json:"type"`

	// Url Canonical public REST URL for the linked resource.
	Url *string `json:"url,omitempty"`
}

// ResourceType defines model for ResourceType.
type ResourceType string

// Space defines model for Space.
type Space struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Description Optional detailed description for the space.
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// IsPublic Whether the space is visible to the organization.
	IsPublic bool `json:"is_public"`

	// IsSystem Whether this is a permanent system space.
	IsSystem bool `json:"is_system"`

	// Name Human-readable space name.
	Name   string        `json:"name"`
	Parent *ResourceLink `json:"parent,omitempty"`

	// Type Public resource type for the space.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// SpaceListItem defines model for SpaceListItem.
type SpaceListItem struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// IsPublic Whether the space is visible to the organization.
	IsPublic bool `json:"is_public"`

	// IsSystem Whether this is a permanent system space.
	IsSystem bool `json:"is_system"`

	// Name Human-readable space name.
	Name   string        `json:"name"`
	Parent *ResourceLink `json:"parent,omitempty"`

	// Type Public resource type for the space.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// Thread defines model for Thread.
type Thread struct {
	CreatedAt time.Time `json:"created_at"`

	// EventsUrl Canonical public REST URL for this thread's paginated events.
	EventsUrl         *string            `json:"events_url,omitempty"`
	Id                openapi_types.UUID `json:"id"`
	LastThreadEventAt *time.Time         `json:"last_thread_event_at"`
}

// ThreadEvent defines model for ThreadEvent.
type ThreadEvent struct {
	Author    ResourceLink                `json:"author"`
	CreatedAt time.Time                   `json:"created_at"`
	Id        openapi_types.UUID          `json:"id"`
	Payloads  []ThreadEvent_Payloads_Item `json:"payloads"`
	UpdatedAt time.Time                   `json:"updated_at"`
}

// ThreadEvent_Payloads_Item defines model for ThreadEvent.payloads.Item.
type ThreadEvent_Payloads_Item struct {
	union json.RawMessage
}

// UpdateAgentRequest defines model for UpdateAgentRequest.
type UpdateAgentRequest struct {
	JobDescription *string `json:"job_description,omitempty"`

	// Model Optional model used by the agent. Set to null to use the configured default model. Omit to leave the current model setting unchanged.
	Model *string `json:"model,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// UpdateCaseRequest defines model for UpdateCaseRequest.
type UpdateCaseRequest struct {
	AssigneeId  *openapi_types.UUID `json:"assignee_id,omitempty"`
	Description *string             `json:"description,omitempty"`
	DueAt       *time.Time          `json:"due_at,omitempty"`

	// ParentCaseId Move the case under a parent Case. Provide exactly one of space_id or parent_case_id when moving a case.
	ParentCaseId *openapi_types.UUID `json:"parent_case_id,omitempty"`

	// SpaceId Move the case to a Space. Provide exactly one of space_id or parent_case_id when moving a case.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Status  *CaseStatus         `json:"status,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
	Title   *string             `json:"title,omitempty"`
}

// UpdateFileRequest defines model for UpdateFileRequest.
type UpdateFileRequest struct {
	// CaseId Move the file to a Case, or clear the parent when null. Provide at most one of space_id or case_id.
	CaseId *openapi_types.UUID `json:"case_id,omitempty"`

	// SpaceId Move the file to a Space, or clear the parent when null. Provide at most one of space_id or case_id.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
}

// UpdateNoteRequest defines model for UpdateNoteRequest.
type UpdateNoteRequest struct {
	Body *string `json:"body,omitempty"`

	// CaseId Move the note to a Case. Provide exactly one of space_id or case_id when moving a note.
	CaseId *openapi_types.UUID `json:"case_id,omitempty"`

	// SpaceId Move the note to a Space. Provide exactly one of space_id or case_id when moving a note.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
	Title   *string             `json:"title,omitempty"`
}

// UpdateProcedureRequest defines model for UpdateProcedureRequest.
type UpdateProcedureRequest struct {
	// Stages Complete replacement list of procedure stages, in desired order. Existing procedure stages omitted from this list are deleted.
	Stages *[]ProcedureStagePatchRequest `json:"stages,omitempty"`

	// Title Human-readable procedure name.
	Title *string `json:"title,omitempty"`
}

// UpdateSpaceRequest defines model for UpdateSpaceRequest.
type UpdateSpaceRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt Timestamp when the user was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the user.
	Id openapi_types.UUID `json:"id"`

	// IsPending True when the user has been invited but has not yet signed in via Zitadel.
	IsPending bool `json:"is_pending"`

	// Name Display name for the user.
	Name string `json:"name"`

	// Type Public resource type for the user.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the user was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ValidationErrorBody defines model for ValidationErrorBody.
type ValidationErrorBody struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Fields Field-specific validation errors, when available.
	Fields *[]ValidationErrorField `json:"fields,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// ValidationErrorField defines model for ValidationErrorField.
type ValidationErrorField struct {
	// Message Human-readable validation error message.
	Message string `json:"message"`

	// Path Request field path where the validation error occurred.
	Path string `json:"path"`

	// Type Machine-readable validation error type.
	Type string `json:"type"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Error ValidationErrorBody `json:"error"`
}

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	// Limit Maximum number of agents to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateAgentParams defines parameters for CreateAgent.
type CreateAgentParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetAgentParams defines parameters for GetAgent.
type GetAgentParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateAgentParams defines parameters for UpdateAgent.
type UpdateAgentParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListCasesParams defines parameters for ListCases.
type ListCasesParams struct {
	// Limit Maximum number of cases to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response. Use it with the same filters and sort options as the request that returned it.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// SpaceId Return root cases directly under this Space.
	SpaceId *openapi_types.UUID `form:"space_id,omitempty" json:"space_id,omitempty"`

	// ParentCaseId Return child cases directly under this parent Case.
	ParentCaseId *openapi_types.UUID `form:"parent_case_id,omitempty" json:"parent_case_id,omitempty"`

	// AssigneeId Return cases assigned to this User.
	AssigneeId *openapi_types.UUID `form:"assignee_id,omitempty" json:"assignee_id,omitempty"`

	// Status Return cases with any of these statuses. Repeat status for multiple values. Supported values are open, started, completed, cancelled, and blocked; unsupported values match no cases.
	Status *[]string `form:"status,omitempty" json:"status,omitempty"`

	// Sort Field to sort by. Use position, created_at, or updated_at.
	Sort *ListCasesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Direction Sort direction. Use asc or desc.
	Direction     *ListCasesParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Authorization *string                   `json:"authorization,omitempty"`
}

// ListCasesParamsSort defines parameters for ListCases.
type ListCasesParamsSort string

// ListCasesParamsDirection defines parameters for ListCases.
type ListCasesParamsDirection string

// CreateCaseParams defines parameters for CreateCase.
type CreateCaseParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteCaseParams defines parameters for DeleteCase.
type DeleteCaseParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetCaseParams defines parameters for GetCase.
type GetCaseParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateCaseParams defines parameters for UpdateCase.
type UpdateCaseParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// Limit Maximum number of files to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response. Use it with the same filters and sort options as the request that returned it.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// SpaceId Return files directly under this Space.
	SpaceId *openapi_types.UUID `form:"space_id,omitempty" json:"space_id,omitempty"`

	// CaseId Return files directly attached to this Case.
	CaseId *openapi_types.UUID `form:"case_id,omitempty" json:"case_id,omitempty"`

	// Sort Field to sort by. Use created_at or updated_at.
	Sort *ListFilesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Direction Sort direction. Use asc or desc.
	Direction     *ListFilesParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Authorization *string                   `json:"authorization,omitempty"`
}

// ListFilesParamsSort defines parameters for ListFiles.
type ListFilesParamsSort string

// ListFilesParamsDirection defines parameters for ListFiles.
type ListFilesParamsDirection string

// CreateFileParams defines parameters for CreateFile.
type CreateFileParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteFileParams defines parameters for DeleteFile.
type DeleteFileParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetFileParams defines parameters for GetFile.
type GetFileParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateFileParams defines parameters for UpdateFile.
type UpdateFileParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	// Limit Maximum number of notes to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response. Use it with the same filters as the request that returned it.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// SpaceId Return notes directly under this Space.
	SpaceId *openapi_types.UUID `form:"space_id,omitempty" json:"space_id,omitempty"`

	// CaseId Return notes directly under this Case.
	CaseId *openapi_types.UUID `form:"case_id,omitempty" json:"case_id,omitempty"`

	// ThreadId Return notes directly under this Thread.
	ThreadId *openapi_types.UUID `form:"thread_id,omitempty" json:"thread_id,omitempty"`

	// Sort Field to sort by. Use created_at or updated_at.
	Sort *ListNotesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Direction Sort direction. Use asc or desc.
	Direction     *ListNotesParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Authorization *string                   `json:"authorization,omitempty"`
}

// ListNotesParamsSort defines parameters for ListNotes.
type ListNotesParamsSort string

// ListNotesParamsDirection defines parameters for ListNotes.
type ListNotesParamsDirection string

// CreateNoteParams defines parameters for CreateNote.
type CreateNoteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteNoteParams defines parameters for DeleteNote.
type DeleteNoteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetNoteParams defines parameters for GetNote.
type GetNoteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateNoteParams defines parameters for UpdateNote.
type UpdateNoteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListProceduresParams defines parameters for ListProcedures.
type ListProceduresParams struct {
	// SpaceId Return procedures owned by this Space.
	SpaceId openapi_types.UUID `form:"space_id" json:"space_id"`

	// Limit Maximum number of procedures to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response. Use it with the same space_id as the request that returned it.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateProcedureParams defines parameters for CreateProcedure.
type CreateProcedureParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteProcedureParams defines parameters for DeleteProcedure.
type DeleteProcedureParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetProcedureParams defines parameters for GetProcedure.
type GetProcedureParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateProcedureParams defines parameters for UpdateProcedure.
type UpdateProcedureParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListSpacesParams defines parameters for ListSpaces.
type ListSpacesParams struct {
	// Limit Maximum number of spaces to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateSpaceParams defines parameters for CreateSpace.
type CreateSpaceParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteSpaceParams defines parameters for DeleteSpace.
type DeleteSpaceParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetSpaceParams defines parameters for GetSpace.
type GetSpaceParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateSpaceParams defines parameters for UpdateSpace.
type UpdateSpaceParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetThreadParams defines parameters for GetThread.
type GetThreadParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListThreadEventsParams defines parameters for ListThreadEvents.
type ListThreadEventsParams struct {
	// Limit Maximum number of thread events to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Direction Sort direction by event creation time. Use asc or desc.
	Direction     *ListThreadEventsParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Authorization *string                          `json:"authorization,omitempty"`
}

// ListThreadEventsParamsDirection defines parameters for ListThreadEvents.
type ListThreadEventsParamsDirection string

// CreateThreadMessageParams defines parameters for CreateThreadMessage.
type CreateThreadMessageParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Limit Maximum number of users to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// GetCurrentUserParams defines parameters for GetCurrentUser.
type GetCurrentUserParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = CreateAgentRequest

// UpdateAgentJSONRequestBody defines body for UpdateAgent for application/json ContentType.
type UpdateAgentJSONRequestBody = UpdateAgentRequest

// CreateCaseJSONRequestBody defines body for CreateCase for application/json ContentType.
type CreateCaseJSONRequestBody = CreateCaseRequest

// UpdateCaseJSONRequestBody defines body for UpdateCase for application/json ContentType.
type UpdateCaseJSONRequestBody = UpdateCaseRequest

// CreateFileMultipartRequestBody defines body for CreateFile for multipart/form-data ContentType.
type CreateFileMultipartRequestBody = CreateFileRequest

// UpdateFileJSONRequestBody defines body for UpdateFile for application/json ContentType.
type UpdateFileJSONRequestBody = UpdateFileRequest

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNoteRequest

// UpdateNoteJSONRequestBody defines body for UpdateNote for application/json ContentType.
type UpdateNoteJSONRequestBody = UpdateNoteRequest

// CreateProcedureJSONRequestBody defines body for CreateProcedure for application/json ContentType.
type CreateProcedureJSONRequestBody = CreateProcedureRequest

// UpdateProcedureJSONRequestBody defines body for UpdateProcedure for application/json ContentType.
type UpdateProcedureJSONRequestBody = UpdateProcedureRequest

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = CreateSpaceRequest

// UpdateSpaceJSONRequestBody defines body for UpdateSpace for application/json ContentType.
type UpdateSpaceJSONRequestBody = UpdateSpaceRequest

// CreateThreadMessageJSONRequestBody defines body for CreateThreadMessage for application/json ContentType.
type CreateThreadMessageJSONRequestBody = CreateMessageRequest

// AsMessagePayload returns the union data inside the ThreadEvent_Payloads_Item as a MessagePayload
func (t ThreadEvent_Payloads_Item) AsMessagePayload() (MessagePayload, error) {
	var body MessagePayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessagePayload overwrites any union data inside the ThreadEvent_Payloads_Item as the provided MessagePayload
func (t *ThreadEvent_Payloads_Item) FromMessagePayload(v MessagePayload) error {
	v.PayloadType = "message"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessagePayload performs a merge with any union data inside the ThreadEvent_Payloads_Item, using the provided MessagePayload
func (t *ThreadEvent_Payloads_Item) MergeMessagePayload(v MessagePayload) error {
	v.PayloadType = "message"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFilePayload returns the union data inside the ThreadEvent_Payloads_Item as a FilePayload
func (t ThreadEvent_Payloads_Item) AsFilePayload() (FilePayload, error) {
	var body FilePayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFilePayload overwrites any union data inside the ThreadEvent_Payloads_Item as the provided FilePayload
func (t *ThreadEvent_Payloads_Item) FromFilePayload(v FilePayload) error {
	v.PayloadType = "file"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFilePayload performs a merge with any union data inside the ThreadEvent_Payloads_Item, using the provided FilePayload
func (t *ThreadEvent_Payloads_Item) MergeFilePayload(v FilePayload) error {
	v.PayloadType = "file"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ThreadEvent_Payloads_Item) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"payload_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ThreadEvent_Payloads_Item) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "file":
		return t.AsFilePayload()
	case "message":
		return t.AsMessagePayload()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ThreadEvent_Payloads_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ThreadEvent_Payloads_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
