// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
)

// Defines values for AgentToolLinkType.
const (
	AgentToolLinkTypeCustom   AgentToolLinkType = "custom"
	AgentToolLinkTypeInternal AgentToolLinkType = "internal"
)

// Valid indicates whether the value is a known member of the AgentToolLinkType enum.
func (e AgentToolLinkType) Valid() bool {
	switch e {
	case AgentToolLinkTypeCustom:
		return true
	case AgentToolLinkTypeInternal:
		return true
	default:
		return false
	}
}

// Defines values for CaseIngestionStatus.
const (
	CaseIngestionStatusCompleted  CaseIngestionStatus = "completed"
	CaseIngestionStatusFailed     CaseIngestionStatus = "failed"
	CaseIngestionStatusPending    CaseIngestionStatus = "pending"
	CaseIngestionStatusProcessing CaseIngestionStatus = "processing"
)

// Valid indicates whether the value is a known member of the CaseIngestionStatus enum.
func (e CaseIngestionStatus) Valid() bool {
	switch e {
	case CaseIngestionStatusCompleted:
		return true
	case CaseIngestionStatusFailed:
		return true
	case CaseIngestionStatusPending:
		return true
	case CaseIngestionStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for CaseIngestionFailedEntryStatus.
const (
	CaseIngestionFailedEntryStatusFailed  CaseIngestionFailedEntryStatus = "failed"
	CaseIngestionFailedEntryStatusSkipped CaseIngestionFailedEntryStatus = "skipped"
	CaseIngestionFailedEntryStatusSuccess CaseIngestionFailedEntryStatus = "success"
)

// Valid indicates whether the value is a known member of the CaseIngestionFailedEntryStatus enum.
func (e CaseIngestionFailedEntryStatus) Valid() bool {
	switch e {
	case CaseIngestionFailedEntryStatusFailed:
		return true
	case CaseIngestionFailedEntryStatusSkipped:
		return true
	case CaseIngestionFailedEntryStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for CaseStatus.
const (
	Blocked   CaseStatus = "blocked"
	Cancelled CaseStatus = "cancelled"
	Completed CaseStatus = "completed"
	Open      CaseStatus = "open"
	Started   CaseStatus = "started"
)

// Valid indicates whether the value is a known member of the CaseStatus enum.
func (e CaseStatus) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Cancelled:
		return true
	case Completed:
		return true
	case Open:
		return true
	case Started:
		return true
	default:
		return false
	}
}

// Defines values for ModelDeploymentLocation.
const (
	EUROPE       ModelDeploymentLocation = "EUROPE"
	GLOBAL       ModelDeploymentLocation = "GLOBAL"
	UNITEDSTATES ModelDeploymentLocation = "UNITED_STATES"
	UNKNOWN      ModelDeploymentLocation = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the ModelDeploymentLocation enum.
func (e ModelDeploymentLocation) Valid() bool {
	switch e {
	case EUROPE:
		return true
	case GLOBAL:
		return true
	case UNITEDSTATES:
		return true
	case UNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for ReasoningEffort.
const (
	HIGH   ReasoningEffort = "HIGH"
	LOW    ReasoningEffort = "LOW"
	MEDIUM ReasoningEffort = "MEDIUM"
	XHIGH  ReasoningEffort = "XHIGH"
)

// Valid indicates whether the value is a known member of the ReasoningEffort enum.
func (e ReasoningEffort) Valid() bool {
	switch e {
	case HIGH:
		return true
	case LOW:
		return true
	case MEDIUM:
		return true
	case XHIGH:
		return true
	default:
		return false
	}
}

// Defines values for ResourceType.
const (
	AGENT     ResourceType = "AGENT"
	CASE      ResourceType = "CASE"
	FILE      ResourceType = "FILE"
	NOTE      ResourceType = "NOTE"
	PROCEDURE ResourceType = "PROCEDURE"
	SECRET    ResourceType = "SECRET"
	SPACE     ResourceType = "SPACE"
	THREAD    ResourceType = "THREAD"
	USER      ResourceType = "USER"
)

// Valid indicates whether the value is a known member of the ResourceType enum.
func (e ResourceType) Valid() bool {
	switch e {
	case AGENT:
		return true
	case CASE:
		return true
	case FILE:
		return true
	case NOTE:
		return true
	case PROCEDURE:
		return true
	case SECRET:
		return true
	case SPACE:
		return true
	case THREAD:
		return true
	case USER:
		return true
	default:
		return false
	}
}

// Defines values for ToolType.
const (
	ToolTypeCustom   ToolType = "custom"
	ToolTypeInternal ToolType = "internal"
)

// Valid indicates whether the value is a known member of the ToolType enum.
func (e ToolType) Valid() bool {
	switch e {
	case ToolTypeCustom:
		return true
	case ToolTypeInternal:
		return true
	default:
		return false
	}
}

// Defines values for ToolListItemType.
const (
	Custom   ToolListItemType = "custom"
	Internal ToolListItemType = "internal"
)

// Valid indicates whether the value is a known member of the ToolListItemType enum.
func (e ToolListItemType) Valid() bool {
	switch e {
	case Custom:
		return true
	case Internal:
		return true
	default:
		return false
	}
}

// Defines values for ListCasesParamsSort.
const (
	ListCasesParamsSortCreatedAt ListCasesParamsSort = "created_at"
	ListCasesParamsSortPosition  ListCasesParamsSort = "position"
	ListCasesParamsSortUpdatedAt ListCasesParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListCasesParamsSort enum.
func (e ListCasesParamsSort) Valid() bool {
	switch e {
	case ListCasesParamsSortCreatedAt:
		return true
	case ListCasesParamsSortPosition:
		return true
	case ListCasesParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListCasesParamsDirection.
const (
	ListCasesParamsDirectionAsc  ListCasesParamsDirection = "asc"
	ListCasesParamsDirectionDesc ListCasesParamsDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListCasesParamsDirection enum.
func (e ListCasesParamsDirection) Valid() bool {
	switch e {
	case ListCasesParamsDirectionAsc:
		return true
	case ListCasesParamsDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsSort.
const (
	ListFilesParamsSortCreatedAt ListFilesParamsSort = "created_at"
	ListFilesParamsSortUpdatedAt ListFilesParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListFilesParamsSort enum.
func (e ListFilesParamsSort) Valid() bool {
	switch e {
	case ListFilesParamsSortCreatedAt:
		return true
	case ListFilesParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsDirection.
const (
	ListFilesParamsDirectionAsc  ListFilesParamsDirection = "asc"
	ListFilesParamsDirectionDesc ListFilesParamsDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListFilesParamsDirection enum.
func (e ListFilesParamsDirection) Valid() bool {
	switch e {
	case ListFilesParamsDirectionAsc:
		return true
	case ListFilesParamsDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListNotesParamsSort.
const (
	CreatedAt ListNotesParamsSort = "created_at"
	UpdatedAt ListNotesParamsSort = "updated_at"
)

// Valid indicates whether the value is a known member of the ListNotesParamsSort enum.
func (e ListNotesParamsSort) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListNotesParamsDirection.
const (
	ListNotesParamsDirectionAsc  ListNotesParamsDirection = "asc"
	ListNotesParamsDirectionDesc ListNotesParamsDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListNotesParamsDirection enum.
func (e ListNotesParamsDirection) Valid() bool {
	switch e {
	case ListNotesParamsDirectionAsc:
		return true
	case ListNotesParamsDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListThreadEventsParamsDirection.
const (
	ListThreadEventsParamsDirectionAsc  ListThreadEventsParamsDirection = "asc"
	ListThreadEventsParamsDirectionDesc ListThreadEventsParamsDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListThreadEventsParamsDirection enum.
func (e ListThreadEventsParamsDirection) Valid() bool {
	switch e {
	case ListThreadEventsParamsDirectionAsc:
		return true
	case ListThreadEventsParamsDirectionDesc:
		return true
	default:
		return false
	}
}

// AdditionalMetadata defines model for AdditionalMetadata.
type AdditionalMetadata map[string]interface{}

// Agent defines model for Agent.
type Agent struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// JobDescription Optional job description used when the agent acts.
	JobDescription *string `json:"job_description,omitempty"`

	// Model Effective model used by the agent. If the stored model is null, the configured default model is used.
	Model string `json:"model"`

	// Name Human-readable agent name.
	Name            string           `json:"name"`
	Parent          *ResourceLink    `json:"parent,omitempty"`
	ReasoningEffort *ReasoningEffort `json:"reasoning_effort,omitempty"`

	// Type Public resource type for the agent.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// AgentListItem defines model for AgentListItem.
type AgentListItem struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// Model Effective model used by the agent. If the stored model is null, the configured default model is used.
	Model string `json:"model"`

	// Name Human-readable agent name.
	Name            string           `json:"name"`
	Parent          *ResourceLink    `json:"parent,omitempty"`
	ReasoningEffort *ReasoningEffort `json:"reasoning_effort,omitempty"`

	// Type Public resource type for the agent.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// AgentToolLink defines model for AgentToolLink.
type AgentToolLink struct {
	// Id Unique identifier for the assigned tool.
	Id openapi_types.UUID `json:"id"`

	// Name Human-readable tool name.
	Name string `json:"name"`

	// Type Whether the assigned tool is custom or built into Interloom.
	Type AgentToolLinkType `json:"type"`

	// Url Canonical public REST URL for the assigned tool.
	Url *string `json:"url,omitempty"`
}

// AgentToolLinkType Whether the assigned tool is custom or built into Interloom.
type AgentToolLinkType string

// ApplyProcedureSpaceTrigger defines model for ApplyProcedureSpaceTrigger.
type ApplyProcedureSpaceTrigger struct {
	// ProcedureId ID of the procedure applied to new cases in the space.
	ProcedureId openapi_types.UUID `json:"procedure_id"`
	TriggerType string             `json:"trigger_type"`
}

// AssigneeSpaceTrigger defines model for AssigneeSpaceTrigger.
type AssigneeSpaceTrigger struct {
	// AssigneeId ID of the person or agent assigned to new cases in the space.
	AssigneeId  openapi_types.UUID `json:"assignee_id"`
	TriggerType string             `json:"trigger_type"`
}

// Case defines model for Case.
type Case struct {
	Assignee *ResourceLink `json:"assignee,omitempty"`

	// CompletedAt Timestamp when the case was completed, if completed.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Description Optional detailed description or instructions for the case.
	Description *string `json:"description,omitempty"`

	// DueAt Optional deadline for the case.
	DueAt *time.Time `json:"due_at,omitempty"`

	// ExternalId Optional caller-provided identifier for linking to an external system.
	ExternalId *string `json:"external_id,omitempty"`

	// Files Files attached to the case, represented as public File links.
	Files *[]ResourceLink `json:"files,omitempty"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`
	Status CaseStatus         `json:"status"`

	// Summary Optional generated or user-provided case summary.
	Summary *string `json:"summary,omitempty"`

	// Tags Tags assigned to the case, represented as simple names.
	Tags   *[]string    `json:"tags,omitempty"`
	Thread ResourceLink `json:"thread"`

	// Title Human-readable case name.
	Title string `json:"title"`

	// Type Public resource type for the case.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// CaseIngestion defines model for CaseIngestion.
type CaseIngestion struct {
	// CreatedAt Timestamp when the batch was created.
	CreatedAt time.Time `json:"created_at"`

	// EndedAt Timestamp when processing ended, or null while unfinished.
	EndedAt *time.Time `json:"ended_at,omitempty"`

	// ErrorCount Manifest entries that failed processing.
	ErrorCount int `json:"error_count"`

	// Id Unique identifier for the case ingestion.
	Id openapi_types.UUID `json:"id"`

	// ProcessedCount Manifest entries processed so far.
	ProcessedCount int          `json:"processed_count"`
	Space          ResourceLink `json:"space"`

	// StartedAt Timestamp when processing started, or null before processing.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status Case ingestion processing status.
	Status CaseIngestionStatus `json:"status"`

	// SuccessCount Manifest entries that created cases.
	SuccessCount int `json:"success_count"`

	// TotalCount Total manifest entries accepted for import.
	TotalCount int `json:"total_count"`
}

// CaseIngestionStatus Case ingestion processing status.
type CaseIngestionStatus string

// CaseIngestionEntryError defines model for CaseIngestionEntryError.
type CaseIngestionEntryError struct {
	// CreatedAt Timestamp when the error was recorded.
	CreatedAt time.Time `json:"created_at"`

	// Error Human-readable failure message.
	Error string `json:"error"`

	// Id Unique identifier for this entry error.
	Id openapi_types.UUID `json:"id"`
}

// CaseIngestionFailedEntry defines model for CaseIngestionFailedEntry.
type CaseIngestionFailedEntry struct {
	// CreatedAt Timestamp when the entry was recorded.
	CreatedAt time.Time `json:"created_at"`

	// Errors Errors recorded for this manifest entry.
	Errors []CaseIngestionEntryError `json:"errors"`

	// ExternalId Manifest external_id for the failed case.
	ExternalId string `json:"external_id"`

	// Id Unique identifier for this manifest entry result.
	Id openapi_types.UUID `json:"id"`

	// LineNumber 1-indexed line number in the manifest.
	LineNumber int `json:"line_number"`

	// Status Entry processing status.
	Status CaseIngestionFailedEntryStatus `json:"status"`
}

// CaseIngestionFailedEntryStatus Entry processing status.
type CaseIngestionFailedEntryStatus string

// CaseListItem defines model for CaseListItem.
type CaseListItem struct {
	Assignee *ResourceLink `json:"assignee,omitempty"`

	// CompletedAt Timestamp when the case was completed, if completed.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// DueAt Optional deadline for the case.
	DueAt *time.Time `json:"due_at,omitempty"`

	// ExternalId Optional caller-provided identifier for linking to an external system.
	ExternalId *string `json:"external_id,omitempty"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`
	Status CaseStatus         `json:"status"`

	// Tags Tags assigned to the case, represented as simple names.
	Tags *[]string `json:"tags,omitempty"`

	// Title Human-readable case name.
	Title string `json:"title"`

	// Type Public resource type for the case.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// CaseStatus defines model for CaseStatus.
type CaseStatus string

// CreateAgentRequest defines model for CreateAgentRequest.
type CreateAgentRequest struct {
	JobDescription *string `json:"job_description,omitempty"`

	// Model Optional model used by the agent. Set to null or omit to use the configured default model. Use GET /models to discover available model ids.
	Model           *string          `json:"model,omitempty"`
	Name            string           `json:"name"`
	ReasoningEffort *ReasoningEffort `json:"reasoning_effort,omitempty"`
}

// CreateCaseIngestionRequest defines model for CreateCaseIngestionRequest.
type CreateCaseIngestionRequest struct {
	// Manifest JSONL manifest file. Each non-blank line describes one case.
	Manifest openapi_types.File `json:"manifest"`

	// SpaceId Target Space ID for imported root cases.
	SpaceId openapi_types.UUID `json:"space_id"`
}

// CreateCaseRequest defines model for CreateCaseRequest.
type CreateCaseRequest struct {
	AssigneeId      *openapi_types.UUID   `json:"assignee_id,omitempty"`
	AttachedFileIds *[]openapi_types.UUID `json:"attached_file_ids,omitempty"`
	Description     *string               `json:"description,omitempty"`
	DueAt           *time.Time            `json:"due_at,omitempty"`
	ExternalId      *string               `json:"external_id,omitempty"`

	// ParentCaseId Parent Case ID for a child case. Provide exactly one of space_id or parent_case_id.
	ParentCaseId *openapi_types.UUID `json:"parent_case_id,omitempty"`

	// SpaceId Target Space ID for a root case. Provide exactly one of space_id or parent_case_id.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
	Title   string              `json:"title"`
}

// CreateFileRequest defines model for CreateFileRequest.
type CreateFileRequest struct {
	// CaseId Target Case ID for a case-owned file. Provide at most one of space_id or case_id.
	CaseId *openapi_types.UUID `json:"case_id,omitempty"`

	// File File to upload.
	File openapi_types.File `json:"file"`

	// SpaceId Target Space ID for a space-owned file. Provide at most one of space_id or case_id.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
}

// CreateMessageRequest defines model for CreateMessageRequest.
type CreateMessageRequest struct {
	// FileIds Optional File IDs to attach to the created thread event.
	FileIds *[]openapi_types.UUID `json:"file_ids,omitempty"`
	Text    string                `json:"text"`
}

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Body *string `json:"body,omitempty"`

	// CaseId Target Case ID. Provide exactly one of space_id or case_id.
	CaseId *openapi_types.UUID `json:"case_id,omitempty"`

	// SpaceId Target Space ID. Provide exactly one of space_id or case_id.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
	Title   string              `json:"title"`
}

// CreateProcedureRequest defines model for CreateProcedureRequest.
type CreateProcedureRequest struct {
	// SpaceId Space ID that owns the procedure.
	SpaceId openapi_types.UUID `json:"space_id"`

	// Title Human-readable procedure name.
	Title string `json:"title"`
}

// CreateSecretRequest defines model for CreateSecretRequest.
type CreateSecretRequest struct {
	// Name Name used to reference the secret.
	Name string `json:"name"`

	// Value Sensitive value to encrypt and store.
	Value string `json:"value"`
}

// CreateSpaceRequest defines model for CreateSpaceRequest.
type CreateSpaceRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateToolRequest defines model for CreateToolRequest.
type CreateToolRequest struct {
	// Description Human-readable tool description.
	Description string `json:"description"`

	// InputSchema JSON Schema describing the custom tool input.
	InputSchema map[string]interface{} `json:"input_schema"`

	// Name Unique name used to call the custom tool.
	Name string `json:"name"`

	// Script Python script executed by the custom tool.
	Script string `json:"script"`

	// SecretIds Secret IDs to associate with the custom tool.
	SecretIds *[]openapi_types.UUID `json:"secret_ids,omitempty"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	// CreatedAt Timestamp when the user was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the user.
	Id openapi_types.UUID `json:"id"`

	// IsDeactivated True when the user's organization membership is archived.
	IsDeactivated bool `json:"is_deactivated"`

	// IsPending True when the user has been invited but has not yet signed in via Zitadel.
	IsPending bool `json:"is_pending"`

	// Name Display name for the user.
	Name         string       `json:"name"`
	Organization Organization `json:"organization"`

	// Type Public resource type for the user.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the user was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// DisabledSpaceTrigger defines model for DisabledSpaceTrigger.
type DisabledSpaceTrigger struct {
	// TriggerType Null when the space has no active triage trigger.
	TriggerType string `json:"trigger_type"`
}

// File defines model for File.
type File struct {
	AdditionalMetadata *AdditionalMetadata `json:"additional_metadata,omitempty"`

	// CreatedAt Timestamp when the file was created.
	CreatedAt time.Time `json:"created_at"`

	// DownloadUrl Short-lived signed URL for downloading the file bytes.
	DownloadUrl string `json:"download_url"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// MimeType Detected MIME type for the file.
	MimeType string `json:"mime_type"`

	// Name Original or generated display name for the file.
	Name   string        `json:"name"`
	Parent *ResourceLink `json:"parent,omitempty"`

	// Size File size in bytes.
	Size int `json:"size"`

	// Tags Tags assigned to the file, represented as simple names.
	Tags *[]string `json:"tags,omitempty"`

	// Type Public resource type for the file.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the file was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// FilePayload defines model for FilePayload.
type FilePayload struct {
	File        ResourceLink `json:"file"`
	PayloadType string       `json:"payload_type"`
}

// GameObject defines model for GameObject.
type GameObject struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`
	Type   ResourceType       `json:"type"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// InvalidToolIdsError defines model for InvalidToolIdsError.
type InvalidToolIdsError struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// InvalidToolIds Tool IDs that are unknown or unavailable to the caller.
	InvalidToolIds []openapi_types.UUID `json:"invalid_tool_ids"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// InvalidToolIdsResponse defines model for InvalidToolIdsResponse.
type InvalidToolIdsResponse struct {
	Error InvalidToolIdsError `json:"error"`
}

// ListAgentsResponse defines model for ListAgentsResponse.
type ListAgentsResponse struct {
	// Data Items in the current page.
	Data []AgentListItem `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListCaseIngestionErrorsResponse defines model for ListCaseIngestionErrorsResponse.
type ListCaseIngestionErrorsResponse struct {
	// Data Items in the current page.
	Data []CaseIngestionFailedEntry `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListCasesResponse defines model for ListCasesResponse.
type ListCasesResponse struct {
	// Data Items in the current page.
	Data []CaseListItem `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListFilesResponse defines model for ListFilesResponse.
type ListFilesResponse struct {
	// Data Items in the current page.
	Data []File `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListModelsResponse defines model for ListModelsResponse.
type ListModelsResponse struct {
	// Data Supported models in display order.
	Data []Model `json:"data"`
}

// ListNotesResponse defines model for ListNotesResponse.
type ListNotesResponse struct {
	// Data Items in the current page.
	Data []NoteListItem `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListProceduresResponse defines model for ListProceduresResponse.
type ListProceduresResponse struct {
	// Data Items in the current page.
	Data []ProcedureSummary `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListSecretsResponse defines model for ListSecretsResponse.
type ListSecretsResponse struct {
	// Data Items in the current page.
	Data []Secret `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListSpacesResponse defines model for ListSpacesResponse.
type ListSpacesResponse struct {
	// Data Items in the current page.
	Data []SpaceListItem `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListThreadEventsResponse defines model for ListThreadEventsResponse.
type ListThreadEventsResponse struct {
	// Data Items in the current page.
	Data []ThreadEvent `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListToolsResponse defines model for ListToolsResponse.
type ListToolsResponse struct {
	// Data Items in the current page.
	Data []ToolListItem `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse struct {
	// Data Items in the current page.
	Data []User `json:"data"`

	// HasMore Whether more items are available after this page.
	HasMore bool `json:"has_more"`

	// NextCursor Opaque cursor for the next page. Pass this value as cursor on the next request with the same filters and sort options.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// MessagePayload defines model for MessagePayload.
type MessagePayload struct {
	PayloadType string `json:"payload_type"`
	Text        string `json:"text"`
}

// Model defines model for Model.
type Model struct {
	Capabilities ModelCapabilities `json:"capabilities"`

	// ContextWindow Maximum input context window in tokens from the model metadata snapshot.
	ContextWindow      *int                    `json:"context_window,omitempty"`
	DeploymentLocation ModelDeploymentLocation `json:"deployment_location"`

	// Description Short model description.
	Description string `json:"description"`

	// DisplayName Human-readable model name.
	DisplayName string `json:"display_name"`

	// Id Stable model id sent back when selecting a model.
	Id string `json:"id"`

	// IsDefault Whether this catalog entry is the deployment default agent model.
	IsDefault bool `json:"is_default"`

	// IsEnabled Whether this catalog entry is enabled for agent selection in the organization.
	IsEnabled bool `json:"is_enabled"`

	// MaxOutputTokens Maximum output tokens from the model metadata snapshot.
	MaxOutputTokens *int `json:"max_output_tokens,omitempty"`

	// Name Provider-local model name.
	Name string `json:"name"`

	// Provider Provider or proxy namespace for the model.
	Provider string `json:"provider"`
}

// ModelCapabilities defines model for ModelCapabilities.
type ModelCapabilities struct {
	Reasoning *ModelReasoningCapability `json:"reasoning,omitempty"`
}

// ModelDeploymentLocation defines model for ModelDeploymentLocation.
type ModelDeploymentLocation string

// ModelReasoningCapability defines model for ModelReasoningCapability.
type ModelReasoningCapability struct {
	DefaultEffort ReasoningEffort `json:"default_effort"`

	// Efforts Supported reasoning effort values for this model.
	Efforts []ReasoningEffort `json:"efforts"`

	// Supported Whether reasoning is supported by this model.
	Supported *bool `json:"supported,omitempty"`
}

// Note defines model for Note.
type Note struct {
	// Body Optional note body.
	Body *string `json:"body,omitempty"`

	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`

	// Tags Tags assigned to the note, represented as simple names.
	Tags *[]string `json:"tags,omitempty"`

	// Title Human-readable note title.
	Title string `json:"title"`

	// Type Public resource type for the note.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// NoteListItem defines model for NoteListItem.
type NoteListItem struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`

	// Tags Tags assigned to the note, represented as simple names.
	Tags *[]string `json:"tags,omitempty"`

	// Title Human-readable note title.
	Title string `json:"title"`

	// Type Public resource type for the note.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// Organization defines model for Organization.
type Organization struct {
	// Id Unique identifier for the organization.
	Id openapi_types.UUID `json:"id"`

	// Name Display name for the organization.
	Name string `json:"name"`

	// Slug URL-safe slug for the organization.
	Slug string `json:"slug"`
}

// Procedure defines model for Procedure.
type Procedure struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`

	// Stages Procedure stages, in procedure order.
	Stages *[]ProcedureStage `json:"stages,omitempty"`

	// Title Human-readable procedure name.
	Title string `json:"title"`

	// Type Public resource type for the procedure.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ProcedureStage defines model for ProcedureStage.
type ProcedureStage struct {
	Assignee *ResourceLink `json:"assignee,omitempty"`

	// CreatedAt Timestamp when the stage was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the procedure stage.
	Id openapi_types.UUID `json:"id"`

	// Instructions Optional instructions for the stage.
	Instructions *string `json:"instructions,omitempty"`

	// Title Optional human-readable stage title.
	Title *string `json:"title,omitempty"`

	// UpdatedAt Timestamp when the stage was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ProcedureStagePatchRequest defines model for ProcedureStagePatchRequest.
type ProcedureStagePatchRequest struct {
	// AssigneeId User ID assigned to the stage, or null for no assignee.
	AssigneeId *openapi_types.UUID `json:"assignee_id"`

	// Id Existing stage ID. Omit to create a new stage.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Instructions Stage instructions, or null for no instructions.
	Instructions *string `json:"instructions"`

	// Title Stage title, or null for no title.
	Title *string `json:"title"`
}

// ProcedureSummary defines model for ProcedureSummary.
type ProcedureSummary struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id     openapi_types.UUID `json:"id"`
	Parent *ResourceLink      `json:"parent,omitempty"`

	// Title Human-readable procedure name.
	Title string `json:"title"`

	// Type Public resource type for the procedure.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ReasoningEffort defines model for ReasoningEffort.
type ReasoningEffort string

// ReferenceTaskSpaceTrigger defines model for ReferenceTaskSpaceTrigger.
type ReferenceTaskSpaceTrigger struct {
	// ReferenceCaseId ID of the case used to refine new cases in the space.
	ReferenceCaseId openapi_types.UUID `json:"reference_case_id"`
	TriggerType     string             `json:"trigger_type"`
}

// ReplaceAgentToolsRequest defines model for ReplaceAgentToolsRequest.
type ReplaceAgentToolsRequest struct {
	ToolIds []openapi_types.UUID `json:"tool_ids"`
}

// ResourceLink defines model for ResourceLink.
type ResourceLink struct {
	// Id Unique identifier for the linked object.
	Id   openapi_types.UUID `json:"id"`
	Type ResourceType       `json:"type"`

	// Url Canonical public REST URL for the linked resource.
	Url *string `json:"url,omitempty"`
}

// ResourceType defines model for ResourceType.
type ResourceType string

// Secret defines model for Secret.
type Secret struct {
	// Id Unique identifier for the secret.
	Id openapi_types.UUID `json:"id"`

	// Name Name used to reference the secret.
	Name string `json:"name"`

	// Type Public resource type for the secret.
	Type *string `json:"type,omitempty"`
}

// Space defines model for Space.
type Space struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Description Optional detailed description for the space.
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// IsPublic Whether the space is visible to the organization.
	IsPublic bool `json:"is_public"`

	// IsSystem Whether this is a permanent system space.
	IsSystem bool `json:"is_system"`

	// Name Human-readable space name.
	Name   string        `json:"name"`
	Parent *ResourceLink `json:"parent,omitempty"`

	// Type Public resource type for the space.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// SpaceListItem defines model for SpaceListItem.
type SpaceListItem struct {
	// CreatedAt Timestamp when the object was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the object.
	Id openapi_types.UUID `json:"id"`

	// IsPublic Whether the space is visible to the organization.
	IsPublic bool `json:"is_public"`

	// IsSystem Whether this is a permanent system space.
	IsSystem bool `json:"is_system"`

	// Name Human-readable space name.
	Name   string        `json:"name"`
	Parent *ResourceLink `json:"parent,omitempty"`

	// Type Public resource type for the space.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the object was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// Thread defines model for Thread.
type Thread struct {
	CreatedAt time.Time `json:"created_at"`

	// EventsUrl Canonical public REST URL for this thread's paginated events.
	EventsUrl         *string            `json:"events_url,omitempty"`
	Id                openapi_types.UUID `json:"id"`
	LastThreadEventAt *time.Time         `json:"last_thread_event_at"`
}

// ThreadEvent defines model for ThreadEvent.
type ThreadEvent struct {
	Author    ResourceLink                `json:"author"`
	CreatedAt time.Time                   `json:"created_at"`
	Id        openapi_types.UUID          `json:"id"`
	Payloads  []ThreadEvent_Payloads_Item `json:"payloads"`
	UpdatedAt time.Time                   `json:"updated_at"`
}

// ThreadEvent_Payloads_Item defines model for ThreadEvent.payloads.Item.
type ThreadEvent_Payloads_Item struct {
	union json.RawMessage
}

// Tool defines model for Tool.
type Tool struct {
	// Description Human-readable tool description.
	Description string `json:"description"`

	// Id Unique identifier for the tool.
	Id openapi_types.UUID `json:"id"`

	// InputSchema JSON Schema describing the input accepted by the tool.
	InputSchema map[string]interface{} `json:"input_schema"`

	// IsEditable Whether the authenticated user manages and can edit the tool.
	IsEditable bool          `json:"is_editable"`
	Manager    *ResourceLink `json:"manager,omitempty"`

	// Name Human-readable tool name.
	Name string `json:"name"`

	// Secrets Accessible secrets associated with the custom tool.
	Secrets []ToolSecret `json:"secrets"`

	// Type Whether the tool is custom or built into Interloom.
	Type ToolType `json:"type"`
}

// ToolType Whether the tool is custom or built into Interloom.
type ToolType string

// ToolListItem defines model for ToolListItem.
type ToolListItem struct {
	// Id Unique identifier for the tool.
	Id openapi_types.UUID `json:"id"`

	// IsEditable Whether the authenticated user manages and can edit the tool.
	IsEditable bool `json:"is_editable"`

	// Name Human-readable tool name.
	Name string `json:"name"`

	// Type Whether the tool is custom or built into Interloom.
	Type ToolListItemType `json:"type"`
}

// ToolListItemType Whether the tool is custom or built into Interloom.
type ToolListItemType string

// ToolSecret defines model for ToolSecret.
type ToolSecret struct {
	// Id Unique identifier for the linked object.
	Id openapi_types.UUID `json:"id"`

	// Name Name used to reference the associated secret.
	Name *string `json:"name,omitempty"`

	// Type Public resource type for the associated secret.
	Type string `json:"type"`

	// Url Canonical public REST URL for the linked resource.
	Url *string `json:"url,omitempty"`
}

// UpdateAgentRequest defines model for UpdateAgentRequest.
type UpdateAgentRequest struct {
	JobDescription *string `json:"job_description,omitempty"`

	// Model Optional model used by the agent. Set to null to use the configured default model. Omit to leave the current model setting unchanged. Use GET /models to discover available model ids.
	Model           *string          `json:"model,omitempty"`
	Name            *string          `json:"name,omitempty"`
	ReasoningEffort *ReasoningEffort `json:"reasoning_effort,omitempty"`
}

// UpdateCaseRequest defines model for UpdateCaseRequest.
type UpdateCaseRequest struct {
	AssigneeId  *openapi_types.UUID `json:"assignee_id,omitempty"`
	Description *string             `json:"description,omitempty"`
	DueAt       *time.Time          `json:"due_at,omitempty"`

	// ParentCaseId Move the case under a parent Case. Provide exactly one of space_id or parent_case_id when moving a case.
	ParentCaseId *openapi_types.UUID `json:"parent_case_id,omitempty"`

	// SpaceId Move the case to a Space. Provide exactly one of space_id or parent_case_id when moving a case.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Status  *CaseStatus         `json:"status,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
	Title   *string             `json:"title,omitempty"`
}

// UpdateFileRequest defines model for UpdateFileRequest.
type UpdateFileRequest struct {
	// CaseId Move the file to a Case, or clear the parent when null. Provide at most one of space_id or case_id.
	CaseId *openapi_types.UUID `json:"case_id,omitempty"`

	// SpaceId Move the file to a Space, or clear the parent when null. Provide at most one of space_id or case_id.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
}

// UpdateNoteRequest defines model for UpdateNoteRequest.
type UpdateNoteRequest struct {
	Body *string `json:"body,omitempty"`

	// CaseId Move the note to a Case. Provide exactly one of space_id or case_id when moving a note.
	CaseId *openapi_types.UUID `json:"case_id,omitempty"`

	// SpaceId Move the note to a Space. Provide exactly one of space_id or case_id when moving a note.
	SpaceId *openapi_types.UUID `json:"space_id,omitempty"`
	Tags    *[]string           `json:"tags,omitempty"`
	Title   *string             `json:"title,omitempty"`
}

// UpdateProcedureRequest defines model for UpdateProcedureRequest.
type UpdateProcedureRequest struct {
	// Stages Complete replacement list of procedure stages, in desired order. Existing procedure stages omitted from this list are deleted.
	Stages *[]ProcedureStagePatchRequest `json:"stages,omitempty"`

	// Title Human-readable procedure name.
	Title *string `json:"title,omitempty"`
}

// UpdateSpaceRequest defines model for UpdateSpaceRequest.
type UpdateSpaceRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateToolRequest defines model for UpdateToolRequest.
type UpdateToolRequest struct {
	// Description Updated tool description. Omit to leave unchanged.
	Description *string `json:"description,omitempty"`

	// InputSchema Updated input JSON Schema. Omit to leave unchanged.
	InputSchema *map[string]interface{} `json:"input_schema,omitempty"`

	// ManagerId New manager user ID. The tool must have no associated secrets, and manager_id cannot be combined with other updates.
	ManagerId *openapi_types.UUID `json:"manager_id,omitempty"`

	// Name Updated unique tool name. Omit to leave unchanged.
	Name *string `json:"name,omitempty"`

	// Script Updated Python script. Omit to leave unchanged.
	Script *string `json:"script,omitempty"`

	// SecretIds Replacement secret ID list. Pass an empty list to remove all secrets; omit to leave unchanged.
	SecretIds *[]openapi_types.UUID `json:"secret_ids,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt Timestamp when the user was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique identifier for the user.
	Id openapi_types.UUID `json:"id"`

	// IsDeactivated True when the user's organization membership is archived.
	IsDeactivated bool `json:"is_deactivated"`

	// IsPending True when the user has been invited but has not yet signed in via Zitadel.
	IsPending bool `json:"is_pending"`

	// Name Display name for the user.
	Name string `json:"name"`

	// Type Public resource type for the user.
	Type *string `json:"type,omitempty"`

	// UpdatedAt Timestamp when the user was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// ValidationErrorBody defines model for ValidationErrorBody.
type ValidationErrorBody struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Fields Field-specific validation errors, when available.
	Fields *[]ValidationErrorField `json:"fields,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// ValidationErrorField defines model for ValidationErrorField.
type ValidationErrorField struct {
	// Message Human-readable validation error message.
	Message string `json:"message"`

	// Path Request field path where the validation error occurred.
	Path string `json:"path"`

	// Type Machine-readable validation error type.
	Type string `json:"type"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Error ValidationErrorBody `json:"error"`
}

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	// Limit Maximum number of agents to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateAgentParams defines parameters for CreateAgent.
type CreateAgentParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetAgentParams defines parameters for GetAgent.
type GetAgentParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateAgentParams defines parameters for UpdateAgent.
type UpdateAgentParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListAgentToolsParams defines parameters for ListAgentTools.
type ListAgentToolsParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ReplaceAgentToolsParams defines parameters for ReplaceAgentTools.
type ReplaceAgentToolsParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ReplaceAgentTools422JSONResponseBody defines parameters for ReplaceAgentTools.
type ReplaceAgentTools422JSONResponseBody struct {
	union json.RawMessage
}

// CreateCaseIngestionParams defines parameters for CreateCaseIngestion.
type CreateCaseIngestionParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetCaseIngestionParams defines parameters for GetCaseIngestion.
type GetCaseIngestionParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListCaseIngestionErrorsParams defines parameters for ListCaseIngestionErrors.
type ListCaseIngestionErrorsParams struct {
	// Limit Maximum number of failed entries to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListCasesParams defines parameters for ListCases.
type ListCasesParams struct {
	// Limit Maximum number of cases to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response. Use it with the same filters and sort options as the request that returned it.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// SpaceId Return root cases directly under this Space.
	SpaceId *openapi_types.UUID `form:"space_id,omitempty" json:"space_id,omitempty"`

	// ParentCaseId Return child cases directly under this parent Case.
	ParentCaseId *openapi_types.UUID `form:"parent_case_id,omitempty" json:"parent_case_id,omitempty"`

	// AssigneeId Return cases assigned to this User.
	AssigneeId *openapi_types.UUID `form:"assignee_id,omitempty" json:"assignee_id,omitempty"`

	// Status Return cases with any of these statuses. Repeat status for multiple values. Supported values are open, started, completed, cancelled, and blocked; unsupported values match no cases.
	Status *[]string `form:"status,omitempty" json:"status,omitempty"`

	// Sort Field to sort by. Use position, created_at, or updated_at.
	Sort *ListCasesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Direction Sort direction. Use asc or desc.
	Direction     *ListCasesParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Authorization *string                   `json:"authorization,omitempty"`
}

// ListCasesParamsSort defines parameters for ListCases.
type ListCasesParamsSort string

// ListCasesParamsDirection defines parameters for ListCases.
type ListCasesParamsDirection string

// CreateCaseParams defines parameters for CreateCase.
type CreateCaseParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteCaseParams defines parameters for DeleteCase.
type DeleteCaseParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetCaseParams defines parameters for GetCase.
type GetCaseParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateCaseParams defines parameters for UpdateCase.
type UpdateCaseParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// Limit Maximum number of files to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response. Use it with the same filters and sort options as the request that returned it.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// SpaceId Return files directly under this Space.
	SpaceId *openapi_types.UUID `form:"space_id,omitempty" json:"space_id,omitempty"`

	// CaseId Return files directly attached to this Case.
	CaseId *openapi_types.UUID `form:"case_id,omitempty" json:"case_id,omitempty"`

	// Sort Field to sort by. Use created_at or updated_at.
	Sort *ListFilesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Direction Sort direction. Use asc or desc.
	Direction     *ListFilesParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Authorization *string                   `json:"authorization,omitempty"`
}

// ListFilesParamsSort defines parameters for ListFiles.
type ListFilesParamsSort string

// ListFilesParamsDirection defines parameters for ListFiles.
type ListFilesParamsDirection string

// CreateFileParams defines parameters for CreateFile.
type CreateFileParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteFileParams defines parameters for DeleteFile.
type DeleteFileParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetFileParams defines parameters for GetFile.
type GetFileParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateFileParams defines parameters for UpdateFile.
type UpdateFileParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListModelsParams defines parameters for ListModels.
type ListModelsParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	// Limit Maximum number of notes to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response. Use it with the same filters as the request that returned it.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// SpaceId Return notes directly under this Space.
	SpaceId *openapi_types.UUID `form:"space_id,omitempty" json:"space_id,omitempty"`

	// CaseId Return notes directly under this Case.
	CaseId *openapi_types.UUID `form:"case_id,omitempty" json:"case_id,omitempty"`

	// ThreadId Return notes directly under this Thread.
	ThreadId *openapi_types.UUID `form:"thread_id,omitempty" json:"thread_id,omitempty"`

	// Sort Field to sort by. Use created_at or updated_at.
	Sort *ListNotesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Direction Sort direction. Use asc or desc.
	Direction     *ListNotesParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Authorization *string                   `json:"authorization,omitempty"`
}

// ListNotesParamsSort defines parameters for ListNotes.
type ListNotesParamsSort string

// ListNotesParamsDirection defines parameters for ListNotes.
type ListNotesParamsDirection string

// CreateNoteParams defines parameters for CreateNote.
type CreateNoteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteNoteParams defines parameters for DeleteNote.
type DeleteNoteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetNoteParams defines parameters for GetNote.
type GetNoteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateNoteParams defines parameters for UpdateNote.
type UpdateNoteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListProceduresParams defines parameters for ListProcedures.
type ListProceduresParams struct {
	// SpaceId Return procedures owned by this Space.
	SpaceId openapi_types.UUID `form:"space_id" json:"space_id"`

	// Limit Maximum number of procedures to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response. Use it with the same space_id as the request that returned it.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateProcedureParams defines parameters for CreateProcedure.
type CreateProcedureParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteProcedureParams defines parameters for DeleteProcedure.
type DeleteProcedureParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetProcedureParams defines parameters for GetProcedure.
type GetProcedureParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateProcedureParams defines parameters for UpdateProcedure.
type UpdateProcedureParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListSecretsParams defines parameters for ListSecrets.
type ListSecretsParams struct {
	// Limit Maximum number of secrets to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateSecretParams defines parameters for CreateSecret.
type CreateSecretParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteSecretParams defines parameters for DeleteSecret.
type DeleteSecretParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListSpacesParams defines parameters for ListSpaces.
type ListSpacesParams struct {
	// Limit Maximum number of spaces to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateSpaceParams defines parameters for CreateSpace.
type CreateSpaceParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteSpaceParams defines parameters for DeleteSpace.
type DeleteSpaceParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetSpaceParams defines parameters for GetSpace.
type GetSpaceParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateSpaceParams defines parameters for UpdateSpace.
type UpdateSpaceParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetSpaceTriggerParams defines parameters for GetSpaceTrigger.
type GetSpaceTriggerParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetSpaceTrigger200JSONResponseBody defines parameters for GetSpaceTrigger.
type GetSpaceTrigger200JSONResponseBody struct {
	union json.RawMessage
}

// UpdateSpaceTriggerJSONBody defines parameters for UpdateSpaceTrigger.
type UpdateSpaceTriggerJSONBody struct {
	union json.RawMessage
}

// UpdateSpaceTriggerParams defines parameters for UpdateSpaceTrigger.
type UpdateSpaceTriggerParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateSpaceTrigger200JSONResponseBody defines parameters for UpdateSpaceTrigger.
type UpdateSpaceTrigger200JSONResponseBody struct {
	union json.RawMessage
}

// GetThreadParams defines parameters for GetThread.
type GetThreadParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListThreadEventsParams defines parameters for ListThreadEvents.
type ListThreadEventsParams struct {
	// Limit Maximum number of thread events to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Direction Sort direction by event creation time. Use asc or desc.
	Direction     *ListThreadEventsParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Authorization *string                          `json:"authorization,omitempty"`
}

// ListThreadEventsParamsDirection defines parameters for ListThreadEvents.
type ListThreadEventsParamsDirection string

// CreateThreadMessageParams defines parameters for CreateThreadMessage.
type CreateThreadMessageParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListToolsParams defines parameters for ListTools.
type ListToolsParams struct {
	// Limit Maximum number of tools to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateToolParams defines parameters for CreateTool.
type CreateToolParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetToolParams defines parameters for GetTool.
type GetToolParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateToolParams defines parameters for UpdateTool.
type UpdateToolParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Limit Maximum number of users to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from next_cursor in a previous response.
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// GetCurrentUserParams defines parameters for GetCurrentUser.
type GetCurrentUserParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = CreateAgentRequest

// UpdateAgentJSONRequestBody defines body for UpdateAgent for application/json ContentType.
type UpdateAgentJSONRequestBody = UpdateAgentRequest

// ReplaceAgentToolsJSONRequestBody defines body for ReplaceAgentTools for application/json ContentType.
type ReplaceAgentToolsJSONRequestBody = ReplaceAgentToolsRequest

// CreateCaseIngestionMultipartRequestBody defines body for CreateCaseIngestion for multipart/form-data ContentType.
type CreateCaseIngestionMultipartRequestBody = CreateCaseIngestionRequest

// CreateCaseJSONRequestBody defines body for CreateCase for application/json ContentType.
type CreateCaseJSONRequestBody = CreateCaseRequest

// UpdateCaseJSONRequestBody defines body for UpdateCase for application/json ContentType.
type UpdateCaseJSONRequestBody = UpdateCaseRequest

// CreateFileMultipartRequestBody defines body for CreateFile for multipart/form-data ContentType.
type CreateFileMultipartRequestBody = CreateFileRequest

// UpdateFileJSONRequestBody defines body for UpdateFile for application/json ContentType.
type UpdateFileJSONRequestBody = UpdateFileRequest

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = CreateNoteRequest

// UpdateNoteJSONRequestBody defines body for UpdateNote for application/json ContentType.
type UpdateNoteJSONRequestBody = UpdateNoteRequest

// CreateProcedureJSONRequestBody defines body for CreateProcedure for application/json ContentType.
type CreateProcedureJSONRequestBody = CreateProcedureRequest

// UpdateProcedureJSONRequestBody defines body for UpdateProcedure for application/json ContentType.
type UpdateProcedureJSONRequestBody = UpdateProcedureRequest

// CreateSecretJSONRequestBody defines body for CreateSecret for application/json ContentType.
type CreateSecretJSONRequestBody = CreateSecretRequest

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = CreateSpaceRequest

// UpdateSpaceJSONRequestBody defines body for UpdateSpace for application/json ContentType.
type UpdateSpaceJSONRequestBody = UpdateSpaceRequest

// UpdateSpaceTriggerJSONRequestBody defines body for UpdateSpaceTrigger for application/json ContentType.
type UpdateSpaceTriggerJSONRequestBody UpdateSpaceTriggerJSONBody

// CreateThreadMessageJSONRequestBody defines body for CreateThreadMessage for application/json ContentType.
type CreateThreadMessageJSONRequestBody = CreateMessageRequest

// CreateToolJSONRequestBody defines body for CreateTool for application/json ContentType.
type CreateToolJSONRequestBody = CreateToolRequest

// UpdateToolJSONRequestBody defines body for UpdateTool for application/json ContentType.
type UpdateToolJSONRequestBody = UpdateToolRequest

// AsMessagePayload returns the union data inside the ThreadEvent_Payloads_Item as a MessagePayload
func (t ThreadEvent_Payloads_Item) AsMessagePayload() (MessagePayload, error) {
	var body MessagePayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessagePayload overwrites any union data inside the ThreadEvent_Payloads_Item as the provided MessagePayload
func (t *ThreadEvent_Payloads_Item) FromMessagePayload(v MessagePayload) error {
	v.PayloadType = "message"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessagePayload performs a merge with any union data inside the ThreadEvent_Payloads_Item, using the provided MessagePayload
func (t *ThreadEvent_Payloads_Item) MergeMessagePayload(v MessagePayload) error {
	v.PayloadType = "message"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFilePayload returns the union data inside the ThreadEvent_Payloads_Item as a FilePayload
func (t ThreadEvent_Payloads_Item) AsFilePayload() (FilePayload, error) {
	var body FilePayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFilePayload overwrites any union data inside the ThreadEvent_Payloads_Item as the provided FilePayload
func (t *ThreadEvent_Payloads_Item) FromFilePayload(v FilePayload) error {
	v.PayloadType = "file"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFilePayload performs a merge with any union data inside the ThreadEvent_Payloads_Item, using the provided FilePayload
func (t *ThreadEvent_Payloads_Item) MergeFilePayload(v FilePayload) error {
	v.PayloadType = "file"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ThreadEvent_Payloads_Item) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"payload_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ThreadEvent_Payloads_Item) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "file":
		return t.AsFilePayload()
	case "message":
		return t.AsMessagePayload()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ThreadEvent_Payloads_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ThreadEvent_Payloads_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsInvalidToolIdsResponse returns the union data inside the ReplaceAgentTools422JSONResponseBody as a InvalidToolIdsResponse
func (t ReplaceAgentTools422JSONResponseBody) AsInvalidToolIdsResponse() (InvalidToolIdsResponse, error) {
	var body InvalidToolIdsResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInvalidToolIdsResponse overwrites any union data inside the ReplaceAgentTools422JSONResponseBody as the provided InvalidToolIdsResponse
func (t *ReplaceAgentTools422JSONResponseBody) FromInvalidToolIdsResponse(v InvalidToolIdsResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInvalidToolIdsResponse performs a merge with any union data inside the ReplaceAgentTools422JSONResponseBody, using the provided InvalidToolIdsResponse
func (t *ReplaceAgentTools422JSONResponseBody) MergeInvalidToolIdsResponse(v InvalidToolIdsResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorResponse returns the union data inside the ReplaceAgentTools422JSONResponseBody as a ValidationErrorResponse
func (t ReplaceAgentTools422JSONResponseBody) AsValidationErrorResponse() (ValidationErrorResponse, error) {
	var body ValidationErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorResponse overwrites any union data inside the ReplaceAgentTools422JSONResponseBody as the provided ValidationErrorResponse
func (t *ReplaceAgentTools422JSONResponseBody) FromValidationErrorResponse(v ValidationErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorResponse performs a merge with any union data inside the ReplaceAgentTools422JSONResponseBody, using the provided ValidationErrorResponse
func (t *ReplaceAgentTools422JSONResponseBody) MergeValidationErrorResponse(v ValidationErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ReplaceAgentTools422JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ReplaceAgentTools422JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAssigneeSpaceTrigger returns the union data inside the GetSpaceTrigger200JSONResponseBody as a AssigneeSpaceTrigger
func (t GetSpaceTrigger200JSONResponseBody) AsAssigneeSpaceTrigger() (AssigneeSpaceTrigger, error) {
	var body AssigneeSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAssigneeSpaceTrigger overwrites any union data inside the GetSpaceTrigger200JSONResponseBody as the provided AssigneeSpaceTrigger
func (t *GetSpaceTrigger200JSONResponseBody) FromAssigneeSpaceTrigger(v AssigneeSpaceTrigger) error {
	v.TriggerType = "assignee"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAssigneeSpaceTrigger performs a merge with any union data inside the GetSpaceTrigger200JSONResponseBody, using the provided AssigneeSpaceTrigger
func (t *GetSpaceTrigger200JSONResponseBody) MergeAssigneeSpaceTrigger(v AssigneeSpaceTrigger) error {
	v.TriggerType = "assignee"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReferenceTaskSpaceTrigger returns the union data inside the GetSpaceTrigger200JSONResponseBody as a ReferenceTaskSpaceTrigger
func (t GetSpaceTrigger200JSONResponseBody) AsReferenceTaskSpaceTrigger() (ReferenceTaskSpaceTrigger, error) {
	var body ReferenceTaskSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReferenceTaskSpaceTrigger overwrites any union data inside the GetSpaceTrigger200JSONResponseBody as the provided ReferenceTaskSpaceTrigger
func (t *GetSpaceTrigger200JSONResponseBody) FromReferenceTaskSpaceTrigger(v ReferenceTaskSpaceTrigger) error {
	v.TriggerType = "reference_task"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReferenceTaskSpaceTrigger performs a merge with any union data inside the GetSpaceTrigger200JSONResponseBody, using the provided ReferenceTaskSpaceTrigger
func (t *GetSpaceTrigger200JSONResponseBody) MergeReferenceTaskSpaceTrigger(v ReferenceTaskSpaceTrigger) error {
	v.TriggerType = "reference_task"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApplyProcedureSpaceTrigger returns the union data inside the GetSpaceTrigger200JSONResponseBody as a ApplyProcedureSpaceTrigger
func (t GetSpaceTrigger200JSONResponseBody) AsApplyProcedureSpaceTrigger() (ApplyProcedureSpaceTrigger, error) {
	var body ApplyProcedureSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApplyProcedureSpaceTrigger overwrites any union data inside the GetSpaceTrigger200JSONResponseBody as the provided ApplyProcedureSpaceTrigger
func (t *GetSpaceTrigger200JSONResponseBody) FromApplyProcedureSpaceTrigger(v ApplyProcedureSpaceTrigger) error {
	v.TriggerType = "apply_procedure"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApplyProcedureSpaceTrigger performs a merge with any union data inside the GetSpaceTrigger200JSONResponseBody, using the provided ApplyProcedureSpaceTrigger
func (t *GetSpaceTrigger200JSONResponseBody) MergeApplyProcedureSpaceTrigger(v ApplyProcedureSpaceTrigger) error {
	v.TriggerType = "apply_procedure"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDisabledSpaceTrigger returns the union data inside the GetSpaceTrigger200JSONResponseBody as a DisabledSpaceTrigger
func (t GetSpaceTrigger200JSONResponseBody) AsDisabledSpaceTrigger() (DisabledSpaceTrigger, error) {
	var body DisabledSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDisabledSpaceTrigger overwrites any union data inside the GetSpaceTrigger200JSONResponseBody as the provided DisabledSpaceTrigger
func (t *GetSpaceTrigger200JSONResponseBody) FromDisabledSpaceTrigger(v DisabledSpaceTrigger) error {
	v.TriggerType = "DisabledSpaceTrigger"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDisabledSpaceTrigger performs a merge with any union data inside the GetSpaceTrigger200JSONResponseBody, using the provided DisabledSpaceTrigger
func (t *GetSpaceTrigger200JSONResponseBody) MergeDisabledSpaceTrigger(v DisabledSpaceTrigger) error {
	v.TriggerType = "DisabledSpaceTrigger"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GetSpaceTrigger200JSONResponseBody) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"trigger_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t GetSpaceTrigger200JSONResponseBody) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "DisabledSpaceTrigger":
		return t.AsDisabledSpaceTrigger()
	case "apply_procedure":
		return t.AsApplyProcedureSpaceTrigger()
	case "assignee":
		return t.AsAssigneeSpaceTrigger()
	case "reference_task":
		return t.AsReferenceTaskSpaceTrigger()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t GetSpaceTrigger200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetSpaceTrigger200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAssigneeSpaceTrigger returns the union data inside the UpdateSpaceTriggerJSONBody as a AssigneeSpaceTrigger
func (t UpdateSpaceTriggerJSONBody) AsAssigneeSpaceTrigger() (AssigneeSpaceTrigger, error) {
	var body AssigneeSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAssigneeSpaceTrigger overwrites any union data inside the UpdateSpaceTriggerJSONBody as the provided AssigneeSpaceTrigger
func (t *UpdateSpaceTriggerJSONBody) FromAssigneeSpaceTrigger(v AssigneeSpaceTrigger) error {
	v.TriggerType = "assignee"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAssigneeSpaceTrigger performs a merge with any union data inside the UpdateSpaceTriggerJSONBody, using the provided AssigneeSpaceTrigger
func (t *UpdateSpaceTriggerJSONBody) MergeAssigneeSpaceTrigger(v AssigneeSpaceTrigger) error {
	v.TriggerType = "assignee"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReferenceTaskSpaceTrigger returns the union data inside the UpdateSpaceTriggerJSONBody as a ReferenceTaskSpaceTrigger
func (t UpdateSpaceTriggerJSONBody) AsReferenceTaskSpaceTrigger() (ReferenceTaskSpaceTrigger, error) {
	var body ReferenceTaskSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReferenceTaskSpaceTrigger overwrites any union data inside the UpdateSpaceTriggerJSONBody as the provided ReferenceTaskSpaceTrigger
func (t *UpdateSpaceTriggerJSONBody) FromReferenceTaskSpaceTrigger(v ReferenceTaskSpaceTrigger) error {
	v.TriggerType = "reference_task"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReferenceTaskSpaceTrigger performs a merge with any union data inside the UpdateSpaceTriggerJSONBody, using the provided ReferenceTaskSpaceTrigger
func (t *UpdateSpaceTriggerJSONBody) MergeReferenceTaskSpaceTrigger(v ReferenceTaskSpaceTrigger) error {
	v.TriggerType = "reference_task"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApplyProcedureSpaceTrigger returns the union data inside the UpdateSpaceTriggerJSONBody as a ApplyProcedureSpaceTrigger
func (t UpdateSpaceTriggerJSONBody) AsApplyProcedureSpaceTrigger() (ApplyProcedureSpaceTrigger, error) {
	var body ApplyProcedureSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApplyProcedureSpaceTrigger overwrites any union data inside the UpdateSpaceTriggerJSONBody as the provided ApplyProcedureSpaceTrigger
func (t *UpdateSpaceTriggerJSONBody) FromApplyProcedureSpaceTrigger(v ApplyProcedureSpaceTrigger) error {
	v.TriggerType = "apply_procedure"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApplyProcedureSpaceTrigger performs a merge with any union data inside the UpdateSpaceTriggerJSONBody, using the provided ApplyProcedureSpaceTrigger
func (t *UpdateSpaceTriggerJSONBody) MergeApplyProcedureSpaceTrigger(v ApplyProcedureSpaceTrigger) error {
	v.TriggerType = "apply_procedure"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDisabledSpaceTrigger returns the union data inside the UpdateSpaceTriggerJSONBody as a DisabledSpaceTrigger
func (t UpdateSpaceTriggerJSONBody) AsDisabledSpaceTrigger() (DisabledSpaceTrigger, error) {
	var body DisabledSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDisabledSpaceTrigger overwrites any union data inside the UpdateSpaceTriggerJSONBody as the provided DisabledSpaceTrigger
func (t *UpdateSpaceTriggerJSONBody) FromDisabledSpaceTrigger(v DisabledSpaceTrigger) error {
	v.TriggerType = "DisabledSpaceTrigger"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDisabledSpaceTrigger performs a merge with any union data inside the UpdateSpaceTriggerJSONBody, using the provided DisabledSpaceTrigger
func (t *UpdateSpaceTriggerJSONBody) MergeDisabledSpaceTrigger(v DisabledSpaceTrigger) error {
	v.TriggerType = "DisabledSpaceTrigger"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UpdateSpaceTriggerJSONBody) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"trigger_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t UpdateSpaceTriggerJSONBody) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "DisabledSpaceTrigger":
		return t.AsDisabledSpaceTrigger()
	case "apply_procedure":
		return t.AsApplyProcedureSpaceTrigger()
	case "assignee":
		return t.AsAssigneeSpaceTrigger()
	case "reference_task":
		return t.AsReferenceTaskSpaceTrigger()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t UpdateSpaceTriggerJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UpdateSpaceTriggerJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAssigneeSpaceTrigger returns the union data inside the UpdateSpaceTrigger200JSONResponseBody as a AssigneeSpaceTrigger
func (t UpdateSpaceTrigger200JSONResponseBody) AsAssigneeSpaceTrigger() (AssigneeSpaceTrigger, error) {
	var body AssigneeSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAssigneeSpaceTrigger overwrites any union data inside the UpdateSpaceTrigger200JSONResponseBody as the provided AssigneeSpaceTrigger
func (t *UpdateSpaceTrigger200JSONResponseBody) FromAssigneeSpaceTrigger(v AssigneeSpaceTrigger) error {
	v.TriggerType = "assignee"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAssigneeSpaceTrigger performs a merge with any union data inside the UpdateSpaceTrigger200JSONResponseBody, using the provided AssigneeSpaceTrigger
func (t *UpdateSpaceTrigger200JSONResponseBody) MergeAssigneeSpaceTrigger(v AssigneeSpaceTrigger) error {
	v.TriggerType = "assignee"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReferenceTaskSpaceTrigger returns the union data inside the UpdateSpaceTrigger200JSONResponseBody as a ReferenceTaskSpaceTrigger
func (t UpdateSpaceTrigger200JSONResponseBody) AsReferenceTaskSpaceTrigger() (ReferenceTaskSpaceTrigger, error) {
	var body ReferenceTaskSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReferenceTaskSpaceTrigger overwrites any union data inside the UpdateSpaceTrigger200JSONResponseBody as the provided ReferenceTaskSpaceTrigger
func (t *UpdateSpaceTrigger200JSONResponseBody) FromReferenceTaskSpaceTrigger(v ReferenceTaskSpaceTrigger) error {
	v.TriggerType = "reference_task"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReferenceTaskSpaceTrigger performs a merge with any union data inside the UpdateSpaceTrigger200JSONResponseBody, using the provided ReferenceTaskSpaceTrigger
func (t *UpdateSpaceTrigger200JSONResponseBody) MergeReferenceTaskSpaceTrigger(v ReferenceTaskSpaceTrigger) error {
	v.TriggerType = "reference_task"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApplyProcedureSpaceTrigger returns the union data inside the UpdateSpaceTrigger200JSONResponseBody as a ApplyProcedureSpaceTrigger
func (t UpdateSpaceTrigger200JSONResponseBody) AsApplyProcedureSpaceTrigger() (ApplyProcedureSpaceTrigger, error) {
	var body ApplyProcedureSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApplyProcedureSpaceTrigger overwrites any union data inside the UpdateSpaceTrigger200JSONResponseBody as the provided ApplyProcedureSpaceTrigger
func (t *UpdateSpaceTrigger200JSONResponseBody) FromApplyProcedureSpaceTrigger(v ApplyProcedureSpaceTrigger) error {
	v.TriggerType = "apply_procedure"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApplyProcedureSpaceTrigger performs a merge with any union data inside the UpdateSpaceTrigger200JSONResponseBody, using the provided ApplyProcedureSpaceTrigger
func (t *UpdateSpaceTrigger200JSONResponseBody) MergeApplyProcedureSpaceTrigger(v ApplyProcedureSpaceTrigger) error {
	v.TriggerType = "apply_procedure"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDisabledSpaceTrigger returns the union data inside the UpdateSpaceTrigger200JSONResponseBody as a DisabledSpaceTrigger
func (t UpdateSpaceTrigger200JSONResponseBody) AsDisabledSpaceTrigger() (DisabledSpaceTrigger, error) {
	var body DisabledSpaceTrigger
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDisabledSpaceTrigger overwrites any union data inside the UpdateSpaceTrigger200JSONResponseBody as the provided DisabledSpaceTrigger
func (t *UpdateSpaceTrigger200JSONResponseBody) FromDisabledSpaceTrigger(v DisabledSpaceTrigger) error {
	v.TriggerType = "DisabledSpaceTrigger"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDisabledSpaceTrigger performs a merge with any union data inside the UpdateSpaceTrigger200JSONResponseBody, using the provided DisabledSpaceTrigger
func (t *UpdateSpaceTrigger200JSONResponseBody) MergeDisabledSpaceTrigger(v DisabledSpaceTrigger) error {
	v.TriggerType = "DisabledSpaceTrigger"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UpdateSpaceTrigger200JSONResponseBody) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"trigger_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t UpdateSpaceTrigger200JSONResponseBody) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "DisabledSpaceTrigger":
		return t.AsDisabledSpaceTrigger()
	case "apply_procedure":
		return t.AsApplyProcedureSpaceTrigger()
	case "assignee":
		return t.AsAssigneeSpaceTrigger()
	case "reference_task":
		return t.AsReferenceTaskSpaceTrigger()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t UpdateSpaceTrigger200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UpdateSpaceTrigger200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
